(tool-bar-mode -1)
(menu-bar-mode -1)
(scroll-bar-mode -1)
(semantic-mode)
(global-auto-revert-mode 1)
(set-face-attribute 'default nil :height 170)
(electric-pair-mode 1)
(global-display-line-numbers-mode 1)
(remove-hook 'text-mode-hook 'turn-on-auto-fill)
(global-auto-revert-mode -1)
'(compilation-message-face 'default)

;; (recentf-mode 1)
;; (savehist-mode 1)
;; (setq history-length 25)
;; (save-place-mode 1)
(fmakunbound 'recentf-mode)
(fmakunbound 'save-place-mode)

(setq inhibit-startup-message t)
(setq make-backup-files nil)
(setq use-dialog-box nil)
(setq global-auto-revert-non-file-buffers t)
(setq display-line-numbers-type 'relative)
(setq ring-bell-function 'ignore)
(setq visible-bell t)
(setq inhibit-startup-message t
      initial-scratch-message ""
      cursor-type 'bar)
(setq indent-line-function 'insert-tab)
(setq c-syntactic-indentation t)
(setq c-basic-offset 4)
(setq truncate-lines t)

(setq-default indent-tabs-mode nil)
(setq-default tab-width 4)
(setq-default electric-indent-mode nil)
(setq-default tab-width 4)
(setq-default indent-tabs-mode nil)
(defalias 'yes-or-no-p 'y-or-n-p)

(when (fboundp 'aggressive-indent-mode)
  (aggressive-indent-mode -1))
