(load "~/.emacs.d/defaults.el")
(mapc #'disable-theme custom-enabled-themes)
(setq custom-file (locate-user-emacs-file "custom.el"))
(load custom-file 'noerror)
(load-theme 'modus-vivendi t)
(load "~/.emacs.d/config.el")
