;;; Automatically generated by ‘recentf’ on Fri Sep 22 20:32:13 2023.

(setq recentf-list
      '(
        "~/.emacs.d/Emacs.org"
        "~/Documents/code/rust/some_project/src/main.rs"
        "/opt/discord/resources/build_info.json"
        "~/.emacs.d/discordrpc.el"
        "~/Documents/code/rust/raylib_test/src/main.rs"
        "~/Documents/code/rust/opengl_game/src/main.rs"
        "~/.emacs.d/var/ido-save-directory-list.el"
        "~/Documents/code/python/game/src/main.py"
        "~/.emacs.d/exwm.el"
        "~/Documents/code/c/roselib/src/main.cxx"
        "/usr/include/c++/13.2.1/bits/stl_vector.h"
        "~/Documents/code/c/roselib/src/os/window.h"
        "~/.emacs.d/init.el"
        "~/.emacs.d/lsp.el"
        "~/Downloads/do_you_like_b.mp3"
        "~/Documents/code/lua/some_project/main.lua"
        "~/.emacs.d/var/emms/history"
        "~/Downloads/1125789.png"
        "~/Downloads/2863.mp4"
        "~/.emacs.d/multi-cursor.el"
        ))

(setq recentf-filter-changer-current 'nil)


;; Local Variables:
;; coding: utf-8-emacs
;; End:
