;;; Automatically generated by ‘recentf’ on Fri Sep 22 20:56:05 2023.

(setq recentf-list
      '(
        "~/.emacs.d/Emacs.org"
        "~/.emacs.d/.gitignore"
        "~/.gitconfig"
        "~/.emacs.d/init.el"
        "~/Documents/code/python/some_project/main.py"
        "~/Documents/code/rust/some_project/src/main.rs"
        "/opt/discord/resources/build_info.json"
        "~/Documents/code/rust/raylib_test/src/main.rs"
        "~/Documents/code/rust/opengl_game/src/main.rs"
        "~/.emacs.d/var/ido-save-directory-list.el"
        "~/Documents/code/python/game/src/main.py"
        "~/Documents/code/c/roselib/src/main.cxx"
        "/usr/include/c++/13.2.1/bits/stl_vector.h"
        "~/Documents/code/c/roselib/src/os/window.h"
        "~/Downloads/do_you_like_b.mp3"
        ))

(setq recentf-filter-changer-current 'nil)


;; Local Variables:
;; coding: utf-8-emacs
;; End:
