;;; doom-modeline-now-playing-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from doom-modeline-now-playing.el

(register-definition-prefixes "doom-modeline-now-playing" '("doom-modeline-now-playing"))

;;; End of scraped data

(provide 'doom-modeline-now-playing-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; doom-modeline-now-playing-autoloads.el ends here
